name: CI - Upload Binaries

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build_mojave:
    name: Zip and Upload Binaries
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clean, strip, and sign binaries
        run: python3 ci.py
      - name: Build DMG
        run: ./build-dmg.sh
      - name: Generate Checksums
        run: sha256sum Universal-Binaries.dmg > sha256sum.txt
      - name: Upload Universal Binaries to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Universal Binaries
          path: Universal-Binaries.dmg
      - name: Upload Checksums to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sha256sum.txt
          path: sha256sum.txt
      - run: |
          mkdir deploy
          mv *.dmg sha256sum.txt deploy/
      - name: Upload to Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@e74ff71f7d8a4c4745b560a485cc5fdb9b5b999d
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: deploy/*
          tag: ${{ github.ref }}
          file_glob: true
