name: CI - Upload Binaries

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

concurrency:  
    cancel-in-progress: true
    group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}


jobs:
  build_mojave:
    name: Zip and Upload Binaries
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dhinakg/import-codesign-certs@v4
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
      - name: Clean, strip, and sign binaries
        run: python3 ci.py
      - name: Tag folder
        run: touch Universal-Binaries/.signed
      - name: Build DMG
        run: ./build-dmg.sh
      - name: Generate Checksums
        run: shasum -a 256 Universal-Binaries.dmg > sha256sum.txt
      - name: Upload Universal Binaries to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Universal Binaries
          path: Universal-Binaries.dmg
      - name: Upload Checksums to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sha256sum.txt
          path: sha256sum.txt
      - run: |
          mkdir deploy
          mv *.dmg sha256sum.txt deploy/
      - name: Upload to Release
        if: github.event_name == 'release' && matrix.os == 'macos-13'
        uses: svenstaro/upload-release-action@1beeb572c19a9242f4361f4cee78f8e0d9aec5df
        with:
          file: deploy/*
          file_glob: true
